export default [
    {
        name:'dashboard',
        icon:'mdi-view-dashboard',
        route:'dashboard'
    },
    {
        name:'graduates',
        icon:'mdi-account-box',
        route:'graduates'
    },
    {
        name:'courses',
        icon:'mdi-school',
        route:'courses'
    },
    {
        name:'Post',
        icon:'mdi-newspaper-variant',
        route:'post'
    },
    {
        name:'Announcement',
        icon:'mdi-bullhorn-outline',
        route:'announcement'
    },
]